import type { DirectorCameraPreset } from "./director-types";

export const DIRECTOR_CAMERA_PRESETS: DirectorCameraPreset[] = [
    {
        id: "front",
        label: "中景",
        description: "正面标准机位，适合人物和商品说明",
        position: [0, 2.2, 6.2],
        target: [0, 1.15, 0],
        fov: 42,
        prompt: "front medium shot, eye-level perspective, balanced framing, commercial reference frame",
        horizontal: 0,
        vertical: 0,
        shotSize: "medium shot",
    },
    {
        id: "close",
        label: "特写",
        description: "靠近主体，适合脸部、手部、产品细节",
        position: [0, 1.9, 3.6],
        target: [0, 1.35, 0],
        fov: 30,
        prompt: "close-up framing, intimate detail shot, shallow perspective, focus on subject detail",
        horizontal: 0,
        vertical: 0,
        shotSize: "close-up",
    },
    {
        id: "wide",
        label: "远景",
        description: "拉开空间，适合展示环境和走位",
        position: [0, 3.0, 9.2],
        target: [0, 1.15, 0],
        fov: 52,
        prompt: "wide full shot, full body in frame, environmental context, clear staging space",
        horizontal: 0,
        vertical: 8,
        shotSize: "full shot",
    },
    {
        id: "overhead",
        label: "俯拍",
        description: "高位向下看，适合桌面、道具摆放和动作关系",
        position: [0.2, 7.4, 3.2],
        target: [0, 0.8, 0],
        fov: 44,
        prompt: "high-angle overhead perspective, viewer above the subject, readable staging from above",
        horizontal: 0,
        vertical: 58,
        shotSize: "medium shot",
    },
    {
        id: "low",
        label: "仰拍",
        description: "低位向上看，适合力量感、英雄感和冲击力",
        position: [0, 0.6, 5.4],
        target: [0, 1.8, 0],
        fov: 38,
        prompt: "low-angle perspective, viewer below the subject, heroic commercial framing",
        horizontal: 0,
        vertical: -30,
        shotSize: "medium shot",
    },
    {
        id: "side",
        label: "侧面",
        description: "侧向观察，适合动作轮廓和运动方向",
        position: [5.8, 2.1, 0.15],
        target: [0, 1.15, 0],
        fov: 40,
        prompt: "true side profile view, 90 degree viewer angle, clear silhouette and action direction",
        horizontal: 90,
        vertical: 0,
        shotSize: "medium shot",
    },
    {
        id: "back",
        label: "背面",
        description: "背后机位，适合出发、观察、悬念和氛围",
        position: [0, 2.2, -5.8],
        target: [0, 1.15, 0],
        fov: 40,
        prompt: "rear view composition, camera behind the subject, no frontal face visible, atmosphere-driven staging",
        horizontal: 180,
        vertical: 0,
        shotSize: "medium shot",
    },
];

export function getDirectorCameraPreset(id?: string) {
    return DIRECTOR_CAMERA_PRESETS.find((preset) => preset.id === id) || DIRECTOR_CAMERA_PRESETS[0];
}
